### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by roma84** [swissup/module-easytabs#30]
![Scherm_afbeelding_2023-04-18_om_15 29 51](https://user-images.githubusercontent.com/2668851/232794812-1033da76-3a06-4df6-9979-5703d38496e7.png)

**Comment by tangar76** [comment]
Easytabs module heavily relies on Magento styles and javascripts. We use `mage/accordion` and `mage/collapsible` JS in this module.

Due to this fact there is no simple solution for the issue _"Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children."_

Here is example how proper tablist mark-up should look - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls#example

```html
<div role="tablist">
  <div role="tab" aria-controls="panel-1">. . .</div>
  . . .
  <div role="tab" aria-controls="panel-N">. . .</div>
</div>

<div role="tabpanel" id="panel-1">. . .</div>
<div role="tabpanel" id="panel-N">. . .</div>
```

And Magento markup is (module use the same):
```html
<div role="tablist">
  <div role="tab">. . .</div>
  <div role="tabpanel" id="panel-1">. . .</div>
  . . .
  <div role="tab">. . .</div>
  <div role="tabpanel" id="panel-N">. . .</div>
</div>
```

That is why first we have to move form Magento JS to our own implementation of tabs.
